### PR TITLE
clean up rari multisigs in rss

### PR DESCRIPTION
**Pull request by DakshMiglani**

### CODE REVIEW

**Comment by transmissions11** [comment]
Thanks!

**Comment by transmissions11** [comment]
Wait @DakshMiglani cna you make a follow up to use .includes instead of index of? 🙏

**Comment by DakshMiglani** [comment]
done #449 @transmissions11

**Comment by transmissions11** [comment]
Oh and I should probably explicitly comment that all the addresses in the rariMultisigs list need to be all lowercase

**Comment by DakshMiglani** [comment]
Or maybe we can just do a ‘map(x => x.toLowerCase())’

Sent via Superhuman iOS ( ***@***.*** )

**Comment by transmissions11** [comment]
> Or maybe we can just do a `map(x => x.toLowerCase())`
> 
> 

Yeah I like that! Can we use the web3 toChecksumAddress instead of toLowerCase tho? 😅🙏

**Pull request merged**
